name: langame
description: Langame, human conversations 2.0.
version: 1.0.0
authors:
  - Louis Beaumont <louis.beaumont@langa.me>

homepage: https://github.com/louis030195/langame-app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: "^1.0.1"
  firebase_auth: "^1.0.1"
  cloud_firestore: "^1.0.1"
  cloud_functions: "^1.0.0"
  google_sign_in: "^5.0.0"
  flutter_facebook_auth: "^3.0.0-nullsafety.1"
  sign_in_with_apple: "^3.0.0"
  crypto: "^3.0.0"
  provider: "^5.0.0"
  http: "^0.13.0"
  after_layout: "^1.0.7+2"
  flutter_staggered_grid_view: "^0.3.4"
  flutter_sound: "^8.0.0+2"
  permission_handler: "^6.0.1"
#  speech_to_text: "^4.0.0"
  protobuf: "^2.0.0"
  flex_color_scheme: "^2.0.0-nullsafety.1"
  shared_preferences: "^2.0.3"
  flutter_launcher_icons: "^0.9.0"
  async: "^2.4.0"
  fluttertoast: "^7.1.6"
  flutter:
    sdk: flutter

flutter_icons:
  image_path_android: "images/chat-flat.png"
  image_path_ios: "images/chat-flat.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

dev_dependencies:
  change_app_package_name: ^0.1.2

#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
