name: langame
description: AI Augmented human conversations
version: 1.1.3+20
authors:
  - Langame <mail@langa.me>

homepage: https://github.com/louis030195/langame-app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # Firebase
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  cloud_functions: ^1.0.5
  firebase_analytics: 8.0.0-dev.0
  firebase_messaging: ^9.1.3
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.3+1
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.0
  flutter_local_notifications: ^5.0.0
  firebase_crashlytics: ^2.0.2
  firebase_remote_config: ^0.9.0-dev.2

  provider: ^5.0.0
  http: ^0.13.0
  after_layout: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  permission_handler: ^6.1.3
  protobuf: ^2.0.0
  flex_color_scheme: ^2.0.0-nullsafety.1
  shared_preferences: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  async: ^2.5.0
  agora_rtc_engine: ^4.0.0-rc.3
  badges: 2.0.0-nullsafety.1
  uuid: ^3.0.2
  material_floating_search_bar: ^0.3.3
  json_annotation: ^4.0.1
  flutter_app_badger: ^1.2.0
  flutter_spinkit: ^5.0.0
  ordered_set: ^3.0.0
  fluttertoast: ^8.0.3
  grouped_list: ^4.0.0
  connectivity: ^3.0.3
  package_info: ^2.0.0
  device_info: ^2.0.0
  url_launcher: ^6.0.3
  feedback: ^1.2.1
  shake: ^1.0.0
  retry: ^3.1.0
  simple_animations: ^3.0.3
  supercharged: ^2.0.0
  tuple: ^2.0.0
  font_awesome_flutter: ^9.0.0
  material_dialogs: ^1.0.0
  lottie: ^1.0.1
  introduction_screen: ^2.1.0
  stripe_payment: ^1.0.11
  flutter:
    sdk: flutter

flutter_icons:
  image_path_android: "images/logo.jpg"
  image_path_ios: "images/logo.jpg"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

dev_dependencies:
  firebase_auth_platform_interface: ^4.0.0
  cloud_firestore_platform_interface: ^4.0.0
  firebase_auth_mocks: ^0.6.0
  google_sign_in_mocks: ^0.2.0
  cloud_firestore_mocks: ^0.8.0
  mockito: ^5.0.2
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  json_serializable: ^4.0.0
  build_runner: ^1.12.2

#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
  - animations/
