name: langame
description: Langame, human conversations 2.0.
version: 1.0.0
authors:
  - Louis Beaumont <louis.beaumont@langa.me>

homepage: https://github.com/louis030195/langame-app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # Firebase
  firebase_core: "^1.0.2"
  firebase_auth: "^1.0.1"
  cloud_firestore: "^1.0.3"
  cloud_functions: "^1.0.2"
  firebase_analytics: 8.0.0-dev.0
  firebase_messaging: "^9.1.0"
  google_sign_in: "^5.0.0"
  flutter_facebook_auth: "^3.0.0-nullsafety.1"
  sign_in_with_apple: "^3.0.0"
  crypto: "^3.0.0"
  flutter_local_notifications: ^5.0.0
  firebase_crashlytics: "^1.0.0"
  firebase_remote_config: "^0.9.0-dev.1"

  provider: "^5.0.0"
  http: "^0.13.0"
  after_layout: "^1.1.0"
  flutter_staggered_grid_view: "^0.3.4"
#  flutter_sound: "^8.0.0+2"
  permission_handler: "^6.0.1"
#  speech_to_text: "^4.0.0"
#  protobuf: "^2.0.0"
  flex_color_scheme: "^2.0.0-nullsafety.1"
  shared_preferences: "^2.0.3"
  flutter_launcher_icons: "^0.9.0"
  async: "^2.4.0"
  agora_rtc_engine: "^4.0.0-rc.3"
#  table_calendar: "3.0.0-nullsafety.1"
  badges: "2.0.0-nullsafety.1"
  uuid: "^3.0.2"
#  quiver: "^3.0.0"
  material_floating_search_bar: "^0.3.3"
  json_annotation: ^4.0.1
  flutter_app_badger: ^1.2.0
  flutter_spinkit: "^5.0.0"
  ordered_set: ^3.0.0
  fluttertoast: ^8.0.3

  flutter:
    sdk: flutter

flutter_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

dev_dependencies:
  firebase_auth_platform_interface: ^4.0.0
  cloud_firestore_platform_interface: ^4.0.0
  firebase_auth_mocks: ^0.6.0
  google_sign_in_mocks: ^0.2.0
  cloud_firestore_mocks: ^0.8.0
  mockito: ^5.0.2
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  json_serializable: ^4.0.0
  build_runner: ^1.12.2

#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
