name: langame
description: Gamified conversations instrumented by AI
version: 1.2.9+45
authors:
  - Langame <contact@langa.me>

homepage: https://github.com/louis030195/langame-app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # Low level

  async: ^2.7.0
  http: ^0.13.3
  package_info: ^2.0.0
  device_info: ^2.0.0
  tuple: ^2.0.0
  connectivity: ^3.0.3
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  permission_handler: ^7.1.0
  crypto: ^3.0.0
  shared_preferences: ^2.0.3
  json_annotation: ^4.0.1

  # Firebase

  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  cloud_functions: ^1.1.0
  firebase_storage: ^8.1.0
  firebase_analytics: ^8.1.0
  firebase_messaging: ^10.0.0
  firebase_crashlytics: ^2.0.4
  firebase_remote_config: ^0.10.0-dev.3
  firebase_dynamic_links: ^2.0.6
  google_sign_in: ^5.0.3
  flutter_facebook_auth: ^3.4.0
  sign_in_with_apple: ^3.0.0
  flutter_local_notifications: ^5.0.0+4
  firebase_app_check: ^0.0.1+2
  

  # Other APIs

  pubnub: 4.0.0-beta.0
  agora_rtc_engine: ^4.0.1
  flutter_stripe: ^1.0.1+2


  # Others

  table_calendar: ^3.0.0
  date_time_picker: ^2.0.0
  clipboard: ^0.1.3
  provider: ^5.0.0
  after_layout: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  protobuf: ^2.0.0
  flex_color_scheme: ^2.0.0-nullsafety.1
  flutter_launcher_icons: ^0.9.0
  badges: 2.0.0-nullsafety.1
  material_floating_search_bar: ^0.3.3
  flutter_app_badger: ^1.2.0
  flutter_spinkit: ^5.0.0
  ordered_set: ^3.0.0
  fluttertoast: ^8.0.6
  grouped_list: ^4.0.0
  feedback: ^1.2.1
  shake: ^1.0.0
  retry: ^3.1.0
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  font_awesome_flutter: ^9.0.0
  material_dialogs: ^1.0.0
  lottie: ^1.0.1
  introduction_screen: ^2.1.0
  share_plus: ^2.1.4
  # share_plus:
  #   git:
  #     url: git@github.com:fluttercommunity/plus_plugins.git
  #     ref: main
  #     path: packages/share_plus/share_plus
  fab_circular_menu: ^1.0.2
  touchable: ^1.0.0
  sortedmap: ^0.5.0
  holding_gesture: ^1.1.0
  # international stuff
  intl: ^0.17.0
  flutter:
    sdk: flutter

flutter_icons:
  image_path_android: "images/logo-android.png"
  image_path_ios: "images/logo-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true

dev_dependencies:
  firebase_auth_mocks: ^0.6.0
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: ^1.1.0
  mockito: ^5.0.2
  test: ^1.17.3
  change_app_package_name: ^1.0.0
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
  - animations/
