name: langame
description: Langame, human conversations 2.0.
version: 1.0.0
authors:
  - Louis Beaumont <louis.beaumont@langa.me>

homepage: https://github.com/louis030195/langame

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: "^1.0.0"
  sign_in_with_apple: "^2.5.2"
  crypto: "^2.1.5"
  flutter_easyloading: "^2.2.2"
  provider: "^4.3.3"
  http: "^0.12.0+4"
  after_layout: "^1.0.7+2"
  get_it: "^4.0.1"
  flutter_staggered_grid_view: "^0.3.4"
  google_fonts: "^0.3.10"
  audio_streamer: "^1.3.0"
  just_audio: "^0.6.14+1"
  flutter_sound: "^7.7.0+1"
  permission_handler: "^5.0.1"
  speech_to_text: "^3.1.0"
  protobuf: "^1.1.3"
  flex_color_scheme: "^1.4.1"
  shared_preferences: "^0.5.12+4"
  flutter_svg: "^0.19.0"
  flutter_launcher_icons: "^0.8.1"
  liquid_swipe: "^1.5.0"
  async: "^2.4.0"
  flutter:
    sdk: flutter

flutter_icons:
  image_path_android: "images/chat-flat.png"
  image_path_ios: "images/chat-flat.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

dev_dependencies:
  change_app_package_name: ^0.1.2

#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
