name: langame
description: Augmented conversations
version: 1.4.8+72
homepage: https://github.com/langa-me/langame-app

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:

  # Low level

  async: ^2.7.0
  http: ^0.13.3
  package_info_plus: ^1.0.3
  device_info_plus: ^2.0.1
  tuple: ^2.0.0
  connectivity: ^3.0.3
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  permission_handler: ^8.1.6
  crypto: ^3.0.0
  shared_preferences: ^2.0.3
  json_annotation: ^4.0.1
  universal_platform: ^1.0.0+1
  # share_plus: ^2.1.4 # unless works on ipad
  share: ^2.0.4
  sentry_flutter: ^6.0.0

  # Firebase

  firebase_core: ^1.3.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.3.0
  cloud_functions: ^3.0.3
  firebase_storage: ^10.0.3
  firebase_analytics: ^8.1.2
  firebase_messaging: ^10.0.3
  firebase_crashlytics: ^2.0.7
  firebase_remote_config: ^0.11.0
  firebase_dynamic_links: ^2.0.6
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  firebase_app_check: ^0.0.1+2

  flutter_local_notifications: ^8.2.0


  # Other APIs

  pubnub: ^4.0.0-beta.1
  agora_rtc_engine: ^4.0.6
  flutter_stripe: ^1.0.1+2


  # Others

  flutter_tts: ^3.2.2
  speech_to_text: ^5.0.0
  table_calendar: ^3.0.0
  date_time_picker: ^2.0.0
  clipboard: ^0.1.3
  provider: ^6.0.0
  after_layout: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  protobuf: ^2.0.0
  flex_color_scheme: ^3.0.1
  flutter_launcher_icons: ^0.9.0
  badges: ^2.0.1
  material_floating_search_bar: ^0.3.3
  flutter_app_badger: ^1.2.0
  flutter_spinkit: ^5.0.0
  ordered_set: ^4.0.0
  fluttertoast: ^8.0.6
  grouped_list: ^4.0.0
  feedback: ^2.0.0
  shake: ^1.0.0
  retry: ^3.1.0
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  font_awesome_flutter: ^9.0.0
  material_dialogs: ^1.0.0
  lottie: ^1.0.1
  introduction_screen: ^2.1.0
  fab_circular_menu: ^1.0.2
  touchable: ^1.0.0
  sortedmap: ^0.5.1
  holding_gesture: ^1.1.0
  algolia: ^1.0.1
      # git:
    #   url: git@github.com:algirdasmac/dart_algolia.git
    #   ref: insights
  # international stuff
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_auth_mocks: ^0.8.1
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: ^1.1.0
  mockito: ^5.0.2
  test: ^1.17.3
  change_app_package_name: ^1.0.0
  json_serializable: ^5.0.1
  build_runner: ^2.0.2
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
  - animations/
