default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_ID_DEV = ENV["DEVELOPER_APP_ID_DEV"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
DEVELOPER_APP_IDENTIFIER_DEV = ENV["DEVELOPER_APP_IDENTIFIER_DEV"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
PROVISIONING_PROFILE_SPECIFIER_DEV = ENV["PROVISIONING_PROFILE_SPECIFIER_DEV"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :beta_prod do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    gym(
      configuration: "Release-prod",
      workspace: "Runner.xcworkspace",
      scheme: "prod",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: false,
      skip_submission: false,
      notify_external_testers: true,
      ipa: "./Runner.ipa",
      changelog: "- Fix issue with push notification",
      distribute_external: true,
      groups: "public",
    )

    delete_temp_keychain(keychain_name)

    firebase_app_distribution(
      app: "1:909899959016:ios:47d44be1ab94dfbfc0575d",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      ipa_path: "./Runner.ipa",
      testers: "louis.beaumont@gmail.com",
    )
  end
  lane :beta_dev do
    begin
      keychain_name = TEMP_KEYCHAIN_USER
      keychain_password = TEMP_KEYCHAIN_PASSWORD
      ensure_temp_keychain(keychain_name, keychain_password)
  
      match(
        type: 'adhoc',
        app_identifier: "me.langa.dev",
        git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
        readonly: true,
        keychain_name: keychain_name,
        keychain_password: keychain_password
      )
      
      gym(
        configuration: "Release-dev",
        workspace: "Runner.xcworkspace",
        scheme: "dev",
        export_method: "ad-hoc",
        export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => "match AdHoc me.langa.dev"
        }
      })

      delete_temp_keychain(keychain_name)

      firebase_app_distribution(
        app: "1:388264600961:ios:cb9793dd455c23e50cf480",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN_DEV"],
        ipa_path: "./Runner.ipa",
        testers: "louis.beaumont@gmail.com",
      )
    end
  end
end
