default_platform(:android)

platform :android do
  desc 'Deploy to closed beta track'
  lane :closed_beta do
    begin
      gradle(task: 'clean')
      gradle(
        task: 'bundle',
        flavor: 'prod',
        build_type: 'Release'
      )
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
        skip_upload_metadata: false,
        skip_upload_images: false,
        skip_upload_screenshots: false,
        release_status: 'completed',
        version_code: flutter_version(
          pubspec_location: '../pubspec.yaml'
        )['version_code'],
      )
    end
  end
end
