name: Flutter manually release web CI/CD

on:
  workflow_dispatch:
    inputs:
      ci:
        description: "CI pipeline name"
        required: false
        default: "ci.yml"

# TODO: should fail if commit is not of format "[version]+[versionCode]:"
jobs:
  deploy_web:
    name: Deploy web version to Firebase hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.8.1
      - run: flutter pub get
      - run: cp web/web_flavors/production/* web
      - run: flutter build web --release
      - name: Set up Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq
      - name: Deploy to Firebase hosting "app.langa.me"
        run: firebase deploy --only hosting:prod-app --token ${{ secrets.FIREBASE_CLI_TOKEN }} --project langame-86ac4

