
name: Flutter release CI/CD

on:
  push:
    branches:
      - main

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Decrypt Android keys
        run: sh ./android/decrypt.sh
        env:
          RELEASE_SECRET_PASSPHRASE: ${{ secrets.RELEASE_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.0.4
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any
#      - name: Format files
#        run: flutter format --set-exit-if-changed .
      - name: Analyze files
        run: flutter analyze .
      - name: Run the tests
        run: flutter test
  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Decrypt Android keys
        run: sh ./android/decrypt.sh
        env:
          RELEASE_SECRET_PASSPHRASE: ${{ secrets.RELEASE_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.0.4
      - name: Install Flutter dependencies
        run: flutter pub get
      - run: flutter build apk --release --flavor prod
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: closed_beta
          subdirectory: android
