name: Backup firebase data regularly
on:
  # Manually trigger the workflow
  workflow_dispatch:
  # And scheduled
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every day at 00:00
    - cron:  '0 0 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: langame-86ac4
          service_account_key: ${{ secrets.GCP_PROD_SA_KEY }}
          export_default_credentials: true

      - name: Set up Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Export all Firestore documents
        run: gcloud firestore export gs://langame-backup

      - name: Export all Firebase authentication users
        run: |
          firebase --token ${{ secrets.FIREBASE_CLI_TOKEN }} auth:export "./firebase-auth-$(date '+%F-%T').json" --format=JSON
          gsutil cp ./firebase-auth-*.json gs://langame-backup/
